name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - branch: SNAPSHOT
            arch: riscv64_generic
    container:
      image: openwrt/sdk:${{ matrix.arch }}-${{ matrix.branch }}
      options: --user root
    defaults: { run: { shell: bash } }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SDK
        working-directory: /builder
        run: HOME=/builder ./setup.sh

      - name: Build package
        id: build
        working-directory: /builder
        env:
          BRANCH: ${{ matrix.branch }}
          ARCH: ${{ matrix.arch }}
        run: |
          echo "src-link byedpi $GITHUB_WORKSPACE" >> feeds.conf
          ./scripts/feeds update byedpi
          ./scripts/feeds install -a -p byedpi
          make defconfig
          make package/byedpi/compile V=s -j$(nproc) BUILD_LOG=1
          make package/index
          tar -C ./bin/packages/*/byedpi -cvf $GITHUB_WORKSPACE/pkg-$BRANCH-$ARCH.tar .

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: pkg-${{ matrix.branch }}-${{ matrix.arch }}
          path: pkg-*.tar
          if-no-files-found: error

  release:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: pkg-*

      - name: Prepare files
        run: |
          mkdir public
          find . -name 'pkg-*.tar' -exec tar -C ./public -xvf {} \;
          rm -f public/Packages* public/manifest public/public.key
          ls -la public/

      - name: Delete old release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release delete gba53229 --repo "$GITHUB_REPOSITORY" --yes --cleanup-tag || true

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          tag_name: gba53229
          name: ByeDPI master ba53229
          body: |
            - Source: [hufrea/byedpi @ ba53229](https://github.com/hufrea/byedpi/commit/ba532298de7b28cfe854aea83d061369d13ca290)
            - Package arch: riscv64_generic
            - OpenWrt: SNAPSHOT
          files: ./public/*
